server:
  port: 8050
  host: "0.0.0.0"
logger:
  level: "error"
  path: "./logs/log.log"
  max-size: 100
  max-age: 30
  max-backups: 3
redis: 
  uri: "redis://redis:6379"

rabbit:
  uri: "amqp://guest:guest@rabbitmq:5672/"

app: 
  cache-ttl: 20
expression-service:
  gorutines-count: 10
  expr-queue: "expression"
  res-queue: "result"
  exchange: "calc"
  route-key: "rpc"
  worker-info-update: 2