version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672 
      - 15672:15672
    restart: always

  redis:  
    image: redis:7.2.3-alpine
    container_name: "redis"  
    ports:  
      - "6379:6379"  
    restart: always 

  front:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: front
    ports:
      - "80:80"

  server:
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - redis
      - rabbitmq
      - front
    container_name: expr
    command: ["/bin/sh", "-c", "/app/wait-for-it.sh rabbitmq:5672 -- /app/main"]
    ports:
      - "8050:8050"
